name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 */6 * * *"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.10.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo apt update && pip3 install -U pip && pip3 install -U -r requirements.txt && python3 -m spr
